FROM imbios/bun-node:1.3.13-current-slim AS base

FROM base AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG APP_URL
ARG NEXT_PUBLIC_DASHBOARD_API_URL
ARG NEXT_PUBLIC_E2B_DOMAIN
ARG NEXT_PUBLIC_E2B_SANDBOX_URL
ARG NEXT_PUBLIC_INFRA_API_URL
ARG NEXT_PUBLIC_ORY_SDK_URL
ARG ORY_HYDRA_PUBLIC_URL
ARG ORY_OAUTH2_AUDIENCE
ARG ORY_OAUTH2_CLI_CLIENT_ID
ARG ORY_OAUTH2_CLIENT_ID
ARG ORY_SDK_URL

ENV APP_URL=$APP_URL
ENV NEXT_PUBLIC_DASHBOARD_API_URL=$NEXT_PUBLIC_DASHBOARD_API_URL
ENV NEXT_PUBLIC_E2B_DOMAIN=$NEXT_PUBLIC_E2B_DOMAIN
ENV NEXT_PUBLIC_E2B_SANDBOX_URL=$NEXT_PUBLIC_E2B_SANDBOX_URL
ENV NEXT_PUBLIC_INFRA_API_URL=$NEXT_PUBLIC_INFRA_API_URL
ENV NEXT_PUBLIC_ORY_SDK_URL=$NEXT_PUBLIC_ORY_SDK_URL
ENV ORY_HYDRA_PUBLIC_URL=$ORY_HYDRA_PUBLIC_URL
ENV ORY_OAUTH2_AUDIENCE=$ORY_OAUTH2_AUDIENCE
ENV ORY_OAUTH2_CLI_CLIENT_ID=$ORY_OAUTH2_CLI_CLIENT_ID
ENV ORY_OAUTH2_CLIENT_ID=$ORY_OAUTH2_CLIENT_ID
ENV ORY_SDK_URL=$ORY_SDK_URL

RUN bun node_modules/next/dist/bin/next build --webpack

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
