/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Health check successful */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['HealthResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/builds': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List team builds */
    get: {
      parameters: {
        query?: {
          /** @description Optional filter by build identifier, template identifier, or template alias. */
          build_id_or_template?: components['parameters']['build_id_or_template']
          /** @description Comma-separated list of build statuses to include. */
          statuses?: components['parameters']['build_statuses']
          /** @description Maximum number of items to return per page. */
          limit?: components['parameters']['builds_limit']
          /** @description Cursor returned by the previous list response in `created_at|build_id` format. */
          cursor?: components['parameters']['builds_cursor']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned paginated builds. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BuildsListResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/builds/statuses': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Build statuses */
    get: {
      parameters: {
        query: {
          /** @description Comma-separated list of build IDs to get statuses for. */
          build_ids: components['parameters']['build_ids']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned build statuses */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BuildsStatusesResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/builds/{build_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Build details */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the build. */
          build_id: components['parameters']['build_id']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned build details. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BuildInfo']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sandboxes/{sandboxID}/record': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Sandbox record */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the sandbox. */
          sandboxID: components['parameters']['sandboxID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned sandbox details. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SandboxRecord']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teams': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List user teams
     * @description Returns all teams the authenticated user belongs to, with limits and default flag.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned user teams. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UserTeamsResponse']
          }
        }
        401: components['responses']['401']
        500: components['responses']['500']
      }
    }
    put?: never
    /** Create team */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateTeamRequest']
        }
      }
      responses: {
        /** @description Successfully created team. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamResolveResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/users/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Bootstrap auth provider user */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminAuthProviderUserBootstrapRequest']
        }
      }
      responses: {
        /** @description Successfully bootstrapped user. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamResolveResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/teams/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Bootstrap team
     * @description Creates and provisions a team for an admin-authenticated bootstrap workflow.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminTeamBootstrapRequest']
        }
      }
      responses: {
        /** @description Successfully bootstrapped team. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamResolveResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        412: components['responses']['412']
        500: components['responses']['500']
        502: components['responses']['502']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/clusters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create a cluster
     * @description Creates a cluster whose configuration cannot be modified.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminClusterCreateRequest']
        }
      }
      responses: {
        /** @description Cluster created. */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AdminClusterCreateResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        409: components['responses']['409']
        500: components['responses']['500']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/clusters/{clusterID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete an unreferenced cluster
     * @description Deletes a cluster after all team assignments are detached and no active environment references remain. Releases soft-deleted environment references in the same transaction while preserving environment and build history. Repeating a completed deletion succeeds.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the cluster. */
          clusterID: components['parameters']['clusterID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Cluster deleted or already absent. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        409: components['responses']['409']
        500: components['responses']['500']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/management/clusters/{clusterID}/destroy-readiness': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check cluster destroy readiness
     * @description Checks whether this exact cluster has active templates or snapshots. Soft-deleted history and team assignments do not block this check. Returns success if the cluster is absent. This read does not change resources or prevent later template creation.
     */
    get: operations['managementClusterDestroyReadiness']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/teams/{teamID}/cluster': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a team's assigned cluster
     * @description Returns the current cluster assignment without exposing cluster credentials.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Cluster assignment returned. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AdminTeamClusterAssignmentResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    /**
     * Assign a cluster to a team
     * @description Updates the team's cluster reference to an existing cluster.
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminTeamClusterAssignmentRequest']
        }
      }
      responses: {
        /** @description Cluster assigned. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        404: components['responses']['404']
        409: components['responses']['409']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/teams/{teamID}/cluster/{clusterID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Detach a cluster from a team
     * @description Clears the assignment only when the team is unassigned or assigned to the specified cluster.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
          /** @description Identifier of the cluster. */
          clusterID: components['parameters']['clusterID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Cluster detached or the team was already unassigned. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        404: components['responses']['404']
        409: components['responses']['409']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/teams/{teamID}/ban': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Ban a team
     * @description Marks the team as banned so its API keys stop authenticating. Idempotent; running workloads are not touched.
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Team banned. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    post?: never
    /**
     * Unban a team
     * @description Clears the team's ban. Idempotent.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Team unbanned. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/teams/{teamID}/block': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Block a team
     * @description Marks the team as blocked with the given reason, so it can no longer start sandboxes or builds. Idempotent; a repeated call replaces the reason.
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminTeamBlockRequest']
        }
      }
      responses: {
        /** @description Team blocked. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    post?: never
    /**
     * Unblock a team
     * @description Clears the team's block and its recorded reason. Idempotent.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Team unblocked. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/user-profiles/resolve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Resolve user profiles */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminAuthProviderProfilesResolveRequest']
        }
      }
      responses: {
        /** @description Successfully resolved profiles. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AdminAuthProviderProfilesResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        500: components['responses']['500']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/user-profiles/by-email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Lookup user profiles by email */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminAuthProviderProfilesLookupEmailRequest']
        }
      }
      responses: {
        /** @description Successfully found matching profiles. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AdminAuthProviderProfilesResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        500: components['responses']['500']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/user-profiles/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** User profile */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the user. */
          userId: components['parameters']['userId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully found profile. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AdminAuthProviderProfilesResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/users/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete user
     * @description Deletes a user by removing the identity provider record, user_identities mapping, and public.users row.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the user. */
          userId: components['parameters']['userId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully deleted user. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        404: components['responses']['404']
        409: components['responses']['409']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teams/resolve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Resolve team identity
     * @description Resolves a team slug to the team's identity, validating the user is a member.
     */
    get: {
      parameters: {
        query: {
          /** @description Team slug to resolve. */
          slug: components['parameters']['teamSlug']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully resolved team. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamResolveResponse']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teams/{teamID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update team */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateTeamRequest']
        }
      }
      responses: {
        /** @description Successfully updated team. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UpdateTeamResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    trace?: never
  }
  '/teams/{teamID}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get team access status
     * @description Returns whether the team is blocked or banned and its recorded blocked reason. Team-authenticated requests may read only the team they are scoped to.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned team access status. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamStatusResponse']
          }
        }
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teams/{teamID}/limits': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get team limits
     * @description Returns the team's tier and effective resource limits. Team-authenticated requests may read only the team they are scoped to.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned team limits. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamLimitsResponse']
          }
        }
        401: components['responses']['401']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teams/{teamID}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List team members */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned team members. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamMembersResponse']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        500: components['responses']['500']
      }
    }
    put?: never
    /** Add team member */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AddTeamMemberRequest']
        }
      }
      responses: {
        /** @description Successfully added team member. */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teams/{teamID}/members/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove team member */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the team. */
          teamID: components['parameters']['teamID']
          /** @description Identifier of the user. */
          userId: components['parameters']['userId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully removed team member. */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        412: components['responses']['412']
        500: components['responses']['500']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List team templates
     * @description Returns a paginated list of the team's templates (and default templates inline, unless the team is on a dedicated cluster), with filtering, search, and column sorting via keyset cursor pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter templates by visibility (true = public, false = internal). */
          public?: components['parameters']['templates_public']
          /** @description Case-insensitive substring match on template names, aliases, and template id. */
          search?: components['parameters']['templates_search']
          /** @description Sort column and direction. */
          sort?: components['parameters']['templates_sort']
          /** @description Maximum number of items to return per page. */
          limit?: components['parameters']['templates_limit']
          /** @description Cursor returned by the previous list response in `{sort}|{value}|{templateID}` format. Rejected if its sort does not match the request. */
          cursor?: components['parameters']['templates_cursor']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned paginated templates. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TeamTemplatesResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/defaults': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List default templates
     * @description Returns the list of default templates with their latest build info and aliases.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned default templates. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DefaultTemplatesResponse']
          }
        }
        401: components['responses']['401']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{templateID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Template
     * @description Returns a single template owned by the current team. Dashboard-shaped read, indexed by template ID.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the template. */
          templateID: components['parameters']['templateID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned the template. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TemplateDetail']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{templateID}/tags/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List template tag groups
     * @description Returns ready template tag assignment groups with bounded per-tag history, paginated over tags with keyset cursor.
     */
    get: {
      parameters: {
        query?: {
          /** @description Maximum number of ready assignment rows to return per tag. */
          assignmentLimit?: components['parameters']['tag_assignment_limit']
          /** @description Maximum number of distinct tags to return per page. */
          tagsLimit?: components['parameters']['tag_groups_limit']
          /** @description Cursor returned by the previous list response in `{sort}|{latest_assigned_at}|{tag}` format (sort-tagged, RFC3339Nano). */
          tagsCursor?: components['parameters']['tag_groups_cursor']
          /** @description Case-insensitive substring filter on tag name. Allowed characters are `a-z`, `0-9`, `.`, `_`, `-`. */
          search?: components['parameters']['tag_groups_search']
          /** @description Sort order for the returned tag groups. */
          sort?: components['parameters']['tag_groups_sort']
        }
        header?: never
        path: {
          /** @description Identifier of the template. */
          templateID: components['parameters']['templateID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned template tag groups. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TemplateTagGroupsResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{templateID}/tags/count': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Count template tags
     * @description Returns the total number of distinct ready tags for the template.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the template. */
          templateID: components['parameters']['templateID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned tag count. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TemplateTagsCountResponse']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{templateID}/tags/exists': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check ready template tag existence
     * @description Checks whether a template tag has at least one ready assignment.
     */
    get: {
      parameters: {
        query: {
          /** @description Template tag name to check. */
          tag: components['parameters']['tag']
        }
        header?: never
        path: {
          /** @description Identifier of the template. */
          templateID: components['parameters']['templateID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully checked template tag existence. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TemplateTagExistsResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{templateID}/tags/{tag}/assignments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List ready assignments for a single template tag
     * @description Returns ready tag assignment events for a single tag, ordered newest first, with keyset cursor pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Cursor returned by the previous list response in `assigned_at|assignment_id` format. */
          cursor?: components['parameters']['tag_assignments_cursor']
          /** @description Maximum number of assignment rows to return per page. */
          limit?: components['parameters']['tag_assignments_limit']
        }
        header?: never
        path: {
          /** @description Identifier of the template. */
          templateID: components['parameters']['templateID']
          /** @description Template tag name. */
          tag: components['parameters']['tag_path']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned tag assignment page. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TemplateTagAssignmentsResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/management/projects/{projectID}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
      }
      cookie?: never
    }
    get?: never
    /** Create or reconcile a project (v1). */
    put: operations['managementUpsertProject']
    post?: never
    /**
     * Delete a project and its control-plane state (v1).
     * @description Declared, and answered with 501 by every control plane. Deleting a project means reclaiming templates, snapshots, volumes, running sandboxes and their stored artifacts, and no single service can reach all of them today. Callers should not depend on this operation until that changes.
     */
    delete: operations['managementDeleteProject']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/management/projects/{projectID}/members/{userID}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
        /** @description Identifier of the user. */
        userID: components['parameters']['userID']
      }
      cookie?: never
    }
    get?: never
    /**
     * Apply one versioned project member projection (v1).
     * @description Applies the newest desired presence for one project member. An older or duplicate revision is accepted without changing target state.
     */
    put: operations['managementApplyProjectMember']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/management/projects/{projectID}/limits': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
      }
      cookie?: never
    }
    get?: never
    /** Reconcile effective limits for a project (v1). */
    put: operations['managementUpsertProjectLimits']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/management/clusters/{clusterID}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    get?: never
    /** Register a cluster (v1). */
    put: operations['managementRegisterCluster']
    post?: never
    /**
     * Delete an unreferenced cluster (v1).
     * @description Deletes a cluster after all team assignments are detached and no active environment references remain. Releases soft-deleted environment references in the same transaction while preserving environment and build history. Repeating a completed deletion succeeds.
     */
    delete: operations['managementDeleteCluster']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/management/projects/{projectID}/cluster/{clusterID}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    get?: never
    /** Assign a cluster to a project (v1). */
    put: operations['managementAssignProjectCluster']
    post?: never
    /** Detach a cluster assignment from a project (v1). */
    delete: operations['managementDetachProjectCluster']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Error: {
      /**
       * Format: int32
       * @description Error code.
       */
      code: number
      /** @description Error message. */
      message: string
    }
    AdminAuthProviderProfile: {
      /**
       * Format: uuid
       * @description Internal E2B user identifier.
       */
      userId: string
      /** @description Email address from the configured auth provider. */
      email: string | null
    }
    AdminAuthProviderProfilesResponse: {
      profiles: components['schemas']['AdminAuthProviderProfile'][]
    }
    AdminAuthProviderProfilesResolveRequest: {
      userIds: string[]
    }
    AdminAuthProviderProfilesLookupEmailRequest: {
      /** Format: email */
      email: string
    }
    AdminAuthProviderUserBootstrapRequest: {
      oidc_issuer: string
      oidc_user_id: string
      /** Format: email */
      oidc_user_email: string
      oidc_user_name?: string | null
      signup_ip?: string
      signup_user_agent?: string
    }
    AdminTeamBootstrapRequest: {
      /** @description Team name. */
      name: string
      /**
       * Format: email
       * @description Billing/contact email for the team.
       */
      email: string
    }
    AdminClusterCreateRequest: {
      /**
       * Format: uuid
       * @description Optional stable identifier for idempotent creation. Reuse succeeds only when the immutable configuration is identical.
       */
      cluster_id?: string
      name: string
      endpoint: string
      endpoint_tls: boolean
      token: string
      sandbox_proxy_domain?: string | null
      auth_org_id?: string | null
    }
    AdminClusterCreateResponse: {
      /** Format: uuid */
      cluster_id: string
    }
    AdminTeamBlockRequest: {
      /** @description Shown to the team as the reason it is blocked. */
      reason: string
    }
    AdminTeamClusterAssignmentRequest: {
      /** Format: uuid */
      cluster_id: string
      /**
       * @description Assign only when the team is unassigned or already assigned to cluster_id.
       * @default false
       */
      preserve_existing: boolean
    }
    AdminTeamClusterAssignmentResponse: {
      /** Format: uuid */
      cluster_id: string
    }
    /**
     * @description Build status mapped for dashboard clients.
     * @enum {string}
     */
    BuildStatus: 'building' | 'failed' | 'success'
    ListedBuild: {
      /**
       * Format: uuid
       * @description Identifier of the build.
       */
      id: string
      /** @description Template alias when present, otherwise template ID. */
      template: string
      /** @description Identifier of the template. */
      templateId: string
      status: components['schemas']['BuildStatus']
      /** @description Failure message when status is `failed`, otherwise `null`. */
      statusMessage: string | null
      /**
       * Format: date-time
       * @description Build creation timestamp in RFC3339 format.
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Build completion timestamp in RFC3339 format, if finished.
       */
      finishedAt: string | null
      /**
       * Format: int64
       * @description CPU cores configured for the build.
       */
      cpuCount: number
      /**
       * Format: int64
       * @description Memory in MiB configured for the build.
       */
      memoryMB: number
      /**
       * Format: int64
       * @description Disk size in MiB configured for the build, if recorded.
       */
      diskSizeMB: number | null
      /** @description envd version the build was created with, if recorded. */
      envdVersion: string | null
    }
    BuildsListResponse: {
      data: components['schemas']['ListedBuild'][]
      /** @description Cursor to pass to the next list request, or `null` if there is no next page. */
      nextCursor: string | null
    }
    BuildStatusItem: {
      /**
       * Format: uuid
       * @description Identifier of the build.
       */
      id: string
      status: components['schemas']['BuildStatus']
      /**
       * Format: date-time
       * @description Build completion timestamp in RFC3339 format, if finished.
       */
      finishedAt: string | null
      /** @description Failure message when status is `failed`, otherwise `null`. */
      statusMessage: string | null
    }
    BuildsStatusesResponse: {
      /** @description List of build statuses */
      buildStatuses: components['schemas']['BuildStatusItem'][]
    }
    BuildInfo: {
      /** @description Template names related to this build, if available. */
      names?: string[] | null
      /**
       * Format: date-time
       * @description Build creation timestamp in RFC3339 format.
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Build completion timestamp in RFC3339 format, if finished.
       */
      finishedAt: string | null
      status: components['schemas']['BuildStatus']
      /** @description Failure message when status is `failed`, otherwise `null`. */
      statusMessage: string | null
    }
    /**
     * Format: int64
     * @description CPU cores for the sandbox
     */
    CPUCount: number
    /**
     * Format: int64
     * @description Memory for the sandbox in MiB
     */
    MemoryMB: number
    /**
     * Format: int64
     * @description Disk size for the sandbox in MiB
     */
    DiskSizeMB: number
    SandboxRecord: {
      /** @description Identifier of the template from which is the sandbox created */
      templateID: string
      /** @description Alias of the template */
      alias?: string
      /** @description Identifier of the sandbox */
      sandboxID: string
      /**
       * Format: date-time
       * @description Time when the sandbox was started
       */
      startedAt: string
      /**
       * Format: date-time
       * @description Time when the sandbox was stopped
       */
      stoppedAt?: string | null
      /** @description Base domain where the sandbox traffic is accessible */
      domain?: string | null
      cpuCount: components['schemas']['CPUCount']
      memoryMB: components['schemas']['MemoryMB']
      diskSizeMB: components['schemas']['DiskSizeMB']
      /** @description Whether the sandbox ended more than the fixed retention window ago, so its monitoring and logs data is no longer available */
      retentionExpired: boolean
      /** @description Whether the sandbox ended more than the team's events retention window ago, so its events data is no longer available */
      eventsRetentionExpired: boolean
    }
    HealthResponse: {
      /** @description Human-readable health check result. */
      message: string
    }
    UserTeamLimits: {
      /** Format: int64 */
      maxLengthHours: number
      /** Format: int64 */
      concurrentSandboxes: number
      /** Format: int64 */
      concurrentTemplateBuilds: number
      /** Format: int64 */
      maxVcpu: number
      /** Format: int64 */
      maxRamMb: number
      /** Format: int64 */
      diskMb: number
      /** Format: int64 */
      eventsTtlDays: number
    }
    TeamLimitsResponse: {
      /** @description The team's raw tier identifier, exactly as stored (not normalized to a catalog plan). */
      tier: string
      limits: components['schemas']['UserTeamLimits']
    }
    UserTeam: {
      /** Format: uuid */
      id: string
      name: string
      slug: string
      tier: string
      email: string
      profilePictureUrl: string | null
      isBlocked: boolean
      isBanned: boolean
      blockedReason: string | null
      isDefault: boolean
      limits: components['schemas']['UserTeamLimits']
      /** Format: date-time */
      createdAt: string
    }
    UserTeamsResponse: {
      teams: components['schemas']['UserTeam'][]
    }
    TeamStatusResponse: {
      isBlocked: boolean
      isBanned: boolean
      blockedReason: string | null
    }
    TeamMember: {
      /** Format: uuid */
      id: string
      email: string
      name?: string | null
      /** Format: uri */
      profilePictureUrl?: string | null
      providers: string[]
      isDefault: boolean
      /** Format: uuid */
      addedBy?: string | null
      /** Format: date-time */
      createdAt: string | null
    }
    TeamMembersResponse: {
      members: components['schemas']['TeamMember'][]
    }
    UpdateTeamRequest: {
      name?: string
      profilePictureUrl?: string | null
    }
    UpdateTeamResponse: {
      /** Format: uuid */
      id: string
      name: string
      profilePictureUrl?: string | null
    }
    AddTeamMemberRequest: {
      /** Format: email */
      email: string
    }
    CreateTeamRequest: {
      name: string
    }
    DefaultTemplateAlias: {
      alias: string
      namespace?: string | null
    }
    DefaultTemplate: {
      id: string
      aliases: components['schemas']['DefaultTemplateAlias'][]
      /** Format: uuid */
      buildId: string
      /** Format: int64 */
      ramMb: number
      /** Format: int64 */
      vcpu: number
      /** Format: int64 */
      totalDiskSizeMb: number | null
      envdVersion?: string | null
      /** Format: date-time */
      createdAt: string
      public: boolean
      /** Format: int32 */
      buildCount: number
      /** Format: int64 */
      spawnCount: number
    }
    DefaultTemplatesResponse: {
      templates: components['schemas']['DefaultTemplate'][]
    }
    TeamTemplate: {
      templateID: string
      /** Format: uuid */
      buildID: string
      /** Format: int64 */
      cpuCount: number
      /** Format: int64 */
      memoryMB: number
      /** Format: int64 */
      diskSizeMB: number | null
      public: boolean
      aliases: string[]
      names: string[]
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
      createdBy: {
        /** Format: uuid */
        id: string
        email?: string | null
      } | null
      /** Format: date-time */
      lastSpawnedAt: string | null
      /** Format: int64 */
      spawnCount: number
      /** Format: int32 */
      buildCount: number
      envdVersion: string | null
      isDefault: boolean
      defaultDescription?: string | null
    }
    TeamTemplatesResponse: {
      data: components['schemas']['TeamTemplate'][]
      /** @description Cursor to pass to the next list request, or `null` if there is no next page. */
      nextCursor: string | null
    }
    /** @description Dashboard-shaped single-template read. Mirrors the infra-api `Template` schema fields the dashboard renders. */
    TemplateDetail: {
      /** @description Identifier of the template. */
      templateID: string
      /** @description Identifier of the latest ready build for the template, or the zero UUID when none. */
      buildID: string
      /** @description vCPU count of the latest ready default build, or `null` when none. */
      cpuCount: components['schemas']['CPUCount'] | null
      /** @description Memory in MiB of the latest ready default build, or `null` when none. */
      memoryMB: components['schemas']['MemoryMB'] | null
      /** @description Disk size in MiB of the latest ready default build, or `null` when none. */
      diskSizeMB: components['schemas']['DiskSizeMB'] | null
      /** @description Whether the template is public or only accessible by the team. */
      public: boolean
      /**
       * @deprecated
       * @description Aliases of the template.
       */
      aliases: string[]
      /** @description Names of the template (namespace/alias format when namespaced). */
      names: string[]
      /**
       * Format: date-time
       * @description Time when the template was created.
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Time when the template was last updated.
       */
      updatedAt: string
      /**
       * Format: date-time
       * @description Time when the template was last used.
       */
      lastSpawnedAt: string | null
      /**
       * Format: int64
       * @description Number of times the template was used.
       */
      spawnCount: number
      /**
       * Format: int32
       * @description Number of times the template was built.
       */
      buildCount: number
      /** @description envd version of the latest ready default build, or `null` when none. */
      envdVersion: string | null
    }
    TemplateTagAssignment: {
      /**
       * Format: uuid
       * @description Identifier of the tag assignment event.
       */
      assignmentId: string
      /**
       * Format: uuid
       * @description Identifier of the assigned build.
       */
      buildId: string
      /**
       * Format: date-time
       * @description Time when the tag was assigned to the build.
       */
      assignedAt: string
      /**
       * Format: date-time
       * @description Time when the assigned build was created.
       */
      buildCreatedAt: string
      /**
       * Format: date-time
       * @description Time when the assigned build finished.
       */
      buildFinishedAt: string | null
    }
    TemplateTagGroup: {
      /** @description Template tag name. */
      tag: string
      /** @description Ready assignment events for this tag, sorted latest first. */
      assignments: components['schemas']['TemplateTagAssignment'][]
      /** @description Whether more ready assignment events exist beyond the requested assignment limit. */
      hasMore: boolean
    }
    TemplateTagGroupsResponse: {
      tags: components['schemas']['TemplateTagGroup'][]
      /** @description Cursor to pass as `tagsCursor` for the next page, or `null` if there is no next page. */
      nextCursor: string | null
    }
    TemplateTagsCountResponse: {
      /**
       * Format: int64
       * @description Total distinct ready tags for the template.
       */
      total: number
    }
    TemplateTagExistsResponse: {
      /** @description Whether the template tag has at least one ready assignment. */
      exists: boolean
      /** @description Normalized template tag name. */
      normalizedTag: string
    }
    TemplateTagAssignmentsResponse: {
      /** @description Ready assignment events for the tag, sorted latest first. */
      data: components['schemas']['TemplateTagAssignment'][]
      /** @description Cursor to pass to the next list request, or `null` if there is no next page. */
      nextCursor: string | null
    }
    TeamResolveResponse: {
      /** Format: uuid */
      id: string
      slug: string
    }
    /**
     * @description The properties of a project this side stores. Every one is synchronized by the caller and sent on every push, so a reconcile is a complete statement of the project rather than a patch.
     *
     *     A project's tier is not among them. It is assigned once, at creation, from this side's own default, and no push moves it — limits arrive separately and in full through upsertProjectLimits, which takes precedence over the tier anyway.
     */
    ManagementProjectUpsertRequest: {
      name: string
      /** @description Changing it renames the project, and nothing follows it. Template names embed the slug they were built under, so a renamed project keeps its existing template names and only new ones carry the new slug. A slug already held on this control plane is a 409, on a rename as much as on a create. */
      slug: string
      /** @description Contact address recorded on the project. */
      email: string
    }
    ManagementProject: components['schemas']['ManagementProjectUpsertRequest'] & {
      /** Format: uuid */
      id: string
    }
    ManagementClusterRegistrationRequest: {
      name: string
      endpoint: string
      endpoint_tls: boolean
      token: string
      sandbox_proxy_domain?: string | null
      auth_org_id?: string | null
    }
    ManagementProjectMemberIdentity: {
      issuer: string
      subject: string
    }
    ManagementProjectMemberApplyRequest: {
      /** Format: int64 */
      revision: number
      present: boolean
      /**
       * @description Whether this membership is the user's default team. Omitted requests from older sources remain non-default.
       * @default false
       */
      is_default: boolean
      identities?: components['schemas']['ManagementProjectMemberIdentity'][]
    }
    /**
     * @description A project's effective limits, already resolved by the caller. Every field is absolute: this side stores what it is given and performs no arithmetic of its own.
     *
     *     The minimums below track the CHECK constraints on tiers, which is the contract for what a limit may be. project_limits stores the same values under looser constraints on purpose — it is a push target, and a floor that only rejects the impossible keeps a future decision about what is allowed a change to this schema rather than a migration.
     *
     *     `max_disk_size_mb` and `max_free_disk_size_mb` are one ceiling under two names, and either name alone carries it. A caller that sends both must send them equal; a caller that sends neither is refused. Sending both is what a caller does while receivers older than the second name are still running.
     */
    ManagementProjectLimits:
      | {
          /**
           * Format: int64
           * @description The caller's version of this answer, raised whenever the limits it resolved for the project change. Delivery is over a network, so two pushes can be in flight at once and arrive in either order: this side stores the revision it accepted and drops a delivery at or below it, which is what keeps a delayed retry from putting the project back on limits it has already left.
           *
           *     Comparable only against earlier revisions for the same project.
           */
          revision: number
          /** Format: int32 */
          concurrent_sandboxes: number
          /** Format: int32 */
          max_sandbox_length_hours: number
          /** Format: int32 */
          max_vcpu: number
          /** Format: int64 */
          max_ram_mb: number
          /** Format: int64 */
          disk_mb: number
          /** Format: int32 */
          concurrent_template_builds: number
          /** Format: int32 */
          events_ttl_days: number
          /**
           * Format: int64
           * @description The default free-space growth target when a template build request omits one. May sit anywhere at or below the maximum free-space growth target, and usually sits well below it; a delivery whose default exceeds the maximum is rejected.
           */
          default_free_disk_size_mb: number
          /**
           * Format: int64
           * @description The most a template build may request as its free-space growth target.
           */
          max_free_disk_size_mb?: number
          /**
           * Format: int64
           * @description The same ceiling as max_free_disk_size_mb, under the name it was first published with. Kept until every deployed sender and receiver speaks the other name.
           */
          max_disk_size_mb?: number
        }
      | unknown
      | unknown
  }
  responses: {
    /** @description Bad request */
    400: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Authentication error */
    401: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Forbidden */
    403: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Not found */
    404: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Conflict */
    409: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Legacy team mutations are disabled */
    412: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Server error */
    500: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Operation is not implemented */
    501: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Upstream error */
    502: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: {
    /** @description Identifier of the build. */
    build_id: string
    /** @description Identifier of the sandbox. */
    sandboxID: string
    /** @description Maximum number of items to return per page. */
    builds_limit: number
    /** @description Cursor returned by the previous list response in `created_at|build_id` format. */
    builds_cursor: string
    /** @description Optional filter by build identifier, template identifier, or template alias. */
    build_id_or_template: string
    /** @description Comma-separated list of build statuses to include. */
    build_statuses: components['schemas']['BuildStatus'][]
    /** @description Comma-separated list of build IDs to get statuses for. */
    build_ids: string[]
    /** @description Identifier of the team. */
    teamID: string
    /** @description Identifier of the cluster. */
    clusterID: string
    /** @description Identifier of the project. */
    projectID: string
    /** @description Identifier of the user. */
    userID: string
    /** @description Identifier of the user. */
    userId: string
    /** @description Team slug to resolve. */
    teamSlug: string
    /** @description Maximum number of items to return per page. */
    templates_limit: number
    /** @description Identifier of the template. */
    templateID: string
    /** @description Template tag name to check. */
    tag: string
    /** @description Maximum number of ready assignment rows to return per tag. */
    tag_assignment_limit: number
    /** @description Template tag name. */
    tag_path: string
    /** @description Maximum number of assignment rows to return per page. */
    tag_assignments_limit: number
    /** @description Cursor returned by the previous list response in `{sort}|{value}|{templateID}` format. Rejected if its sort does not match the request. */
    templates_cursor: string
    /** @description Filter templates by visibility (true = public, false = internal). */
    templates_public: boolean
    /** @description Case-insensitive substring match on template names, aliases, and template id. */
    templates_search: string
    /** @description Sort column and direction. */
    templates_sort:
      | 'created_at_asc'
      | 'created_at_desc'
      | 'updated_at_asc'
      | 'updated_at_desc'
    /** @description Cursor returned by the previous list response in `assigned_at|assignment_id` format. */
    tag_assignments_cursor: string
    /** @description Maximum number of distinct tags to return per page. */
    tag_groups_limit: number
    /** @description Cursor returned by the previous list response in `{sort}|{latest_assigned_at}|{tag}` format (sort-tagged, RFC3339Nano). */
    tag_groups_cursor: string
    /** @description Case-insensitive substring filter on tag name. Allowed characters are `a-z`, `0-9`, `.`, `_`, `-`. */
    tag_groups_search: string
    /** @description Sort order for the returned tag groups. */
    tag_groups_sort: 'latest_desc' | 'latest_asc' | 'name_asc' | 'name_desc'
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  managementClusterDestroyReadiness: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No active templates or snapshots reference the cluster. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['400']
      401: components['responses']['401']
      /** @description Active templates or snapshots must be deleted before destroying the cluster. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      500: components['responses']['500']
    }
  }
  managementUpsertProject: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ManagementProjectUpsertRequest']
      }
    }
    responses: {
      /** @description Existing project reconciled. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ManagementProject']
        }
      }
      /** @description Project created. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ManagementProject']
        }
      }
      400: components['responses']['400']
      401: components['responses']['401']
      409: components['responses']['409']
      500: components['responses']['500']
      501: components['responses']['501']
    }
  }
  managementDeleteProject: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project state is absent. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['400']
      401: components['responses']['401']
      500: components['responses']['500']
      501: components['responses']['501']
    }
  }
  managementApplyProjectMember: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
        /** @description Identifier of the user. */
        userID: components['parameters']['userID']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ManagementProjectMemberApplyRequest']
      }
    }
    responses: {
      /** @description Membership projection is applied or already superseded. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['400']
      401: components['responses']['401']
      404: components['responses']['404']
      409: components['responses']['409']
      500: components['responses']['500']
    }
  }
  managementUpsertProjectLimits: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ManagementProjectLimits']
      }
    }
    responses: {
      /** @description Effective limits are synchronized. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['400']
      401: components['responses']['401']
      404: components['responses']['404']
      500: components['responses']['500']
      501: components['responses']['501']
    }
  }
  managementRegisterCluster: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ManagementClusterRegistrationRequest']
      }
    }
    responses: {
      /** @description Cluster registration is present. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['400']
      401: components['responses']['401']
      409: components['responses']['409']
      500: components['responses']['500']
    }
  }
  managementDeleteCluster: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cluster is absent. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['401']
      409: components['responses']['409']
      500: components['responses']['500']
    }
  }
  managementAssignProjectCluster: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cluster is assigned to the project. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['400']
      401: components['responses']['401']
      404: components['responses']['404']
      409: components['responses']['409']
      500: components['responses']['500']
    }
  }
  managementDetachProjectCluster: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Identifier of the project. */
        projectID: components['parameters']['projectID']
        /** @description Identifier of the cluster. */
        clusterID: components['parameters']['clusterID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The matching assignment is absent. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['401']
      404: components['responses']['404']
      409: components['responses']['409']
      500: components['responses']['500']
    }
  }
}
