export const SANDBOXES_METRICS_POLLING_MS = 3_000

export const SANDBOXES_DETAILS_METRICS_POLLING_MS = 3_000

export const TEAM_METRICS_INITIAL_RANGE_MS = 60 * 60 * 1000 // 1 hour

export const TEAM_METRICS_POLLING_INTERVAL_MS = 30_000

export const TEAM_METRICS_LIVE_CONCURRENT_SANDBOXES_RANGE = 1000 * 60 * 15 // 15 minutes
