export const TERMINAL_SANDBOX_TIMEOUT_MS = 30 * 60 * 1000
export const DEFAULT_COLS = 100
export const DEFAULT_ROWS = 28
export const DEFAULT_PANEL_HEIGHT = 260
export const MAX_TERMINAL_TRANSCRIPT_CHARS = 200_000
export const TERMINAL_PTY_SETTINGS_COOKIE_PREFIX = 'dashboard-terminal-pty'
export const TERMINAL_SESSION_STORAGE_PREFIX = 'dashboard-terminal-session'
export const TERMINAL_AUTOSTART_DEBOUNCE_MS = 300
export const TERMINAL_ATTACH_ATTEMPT_TIMEOUT_MS = 15_000
