import {
  millisecondsInDay,
  millisecondsInHour,
  millisecondsInMinute,
  millisecondsInSecond,
} from 'date-fns/constants'

export const SANDBOX_MONITORING_METRICS_RETENTION_MS = 7 * millisecondsInDay
export const SANDBOX_MONITORING_DEFAULT_RANGE_MS = millisecondsInHour
export const SANDBOX_MONITORING_MIN_RANGE_MS = 10 * millisecondsInSecond
export const SANDBOX_MONITORING_MAX_RANGE_MS = 31 * millisecondsInDay
export const SANDBOX_MONITORING_LIFECYCLE_PADDING_STEPS = 2
export const SANDBOX_MONITORING_MIN_TIMESTAMP_MS = -8_640_000_000_000_000
export const SANDBOX_MONITORING_MAX_TIMESTAMP_MS = 8_640_000_000_000_000

export const SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_ID = 'full-lifecycle'
export const SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_SHORTCUT = 'FULL'
export const SANDBOX_MONITORING_FIRST_1_MINUTE_PRESET_ID = 'first-1m'
export const SANDBOX_MONITORING_FIRST_1_MINUTE_PRESET_SHORTCUT = 'F1'
export const SANDBOX_MONITORING_FIRST_5_MINUTES_PRESET_ID = 'first-5m'
export const SANDBOX_MONITORING_FIRST_5_MINUTES_PRESET_SHORTCUT = 'F5'
export const SANDBOX_MONITORING_LAST_1_MINUTE_PRESET_ID = 'last-1m'
export const SANDBOX_MONITORING_LAST_1_MINUTE_PRESET_SHORTCUT = 'L1'
export const SANDBOX_MONITORING_LAST_5_MINUTES_PRESET_ID = 'last-5m'
export const SANDBOX_MONITORING_LAST_5_MINUTES_PRESET_SHORTCUT = 'L5'
export const SANDBOX_MONITORING_LAST_15_MINUTES_PRESET_ID = 'last-15m'
export const SANDBOX_MONITORING_LAST_15_MINUTES_PRESET_SHORTCUT = 'L15'
export const SANDBOX_MONITORING_LAST_30_MINUTES_PRESET_ID = 'last-30m'
export const SANDBOX_MONITORING_LAST_30_MINUTES_PRESET_SHORTCUT = 'L30'

export const SANDBOX_MONITORING_DEFAULT_PRESET_ID =
  SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_ID

export const SANDBOX_MONITORING_CPU_SERIES_ID = 'cpu'
export const SANDBOX_MONITORING_RAM_SERIES_ID = 'ram'
export const SANDBOX_MONITORING_DISK_SERIES_ID = 'disk'
export const SANDBOX_MONITORING_CPU_SERIES_LABEL = 'CPU'
export const SANDBOX_MONITORING_RAM_SERIES_LABEL = 'RAM'
export const SANDBOX_MONITORING_DISK_SERIES_LABEL = 'DISK'

export const SANDBOX_MONITORING_CPU_INDICATOR_CLASS = 'bg-graph-3'
export const SANDBOX_MONITORING_RAM_INDICATOR_CLASS = 'bg-graph-1'
export const SANDBOX_MONITORING_DISK_INDICATOR_CLASS = 'bg-graph-2'
export const SANDBOX_MONITORING_CPU_LINE_COLOR_VAR = '--graph-3'
export const SANDBOX_MONITORING_CPU_AREA_COLOR_VAR = '--graph-area-3-from'
export const SANDBOX_MONITORING_CPU_AREA_TO_COLOR_VAR = '--graph-area-3-to'
export const SANDBOX_MONITORING_RAM_LINE_COLOR_VAR = '--graph-1'
export const SANDBOX_MONITORING_RAM_AREA_COLOR_VAR = '--graph-area-1-from'
export const SANDBOX_MONITORING_RAM_AREA_TO_COLOR_VAR = '--graph-area-1-to'
export const SANDBOX_MONITORING_DISK_LINE_COLOR_VAR = '--graph-2'
export const SANDBOX_MONITORING_DISK_AREA_COLOR_VAR = '--graph-area-2-from'
export const SANDBOX_MONITORING_DISK_AREA_TO_COLOR_VAR = '--graph-area-2-to'

export const SANDBOX_MONITORING_LIVE_POLLING_MS = 5_000
export const SANDBOX_MONITORING_CUSTOM_END_FUTURE_MS = millisecondsInHour
export const SANDBOX_MONITORING_OVERFETCH_RATIO = 0.02
export const SANDBOX_MONITORING_OVERFETCH_MIN_MS = 30 * millisecondsInSecond
export const SANDBOX_MONITORING_LIVE_DATA_THRESHOLD_MS =
  2 * millisecondsInMinute

export const SANDBOX_MONITORING_CHART_STROKE_VAR = '--stroke'
export const SANDBOX_MONITORING_CHART_FALLBACK_STROKE = '#000'
export const SANDBOX_MONITORING_CHART_LINE_WIDTH = 1
export const SANDBOX_MONITORING_CHART_FG_VAR = '--fg'
export const SANDBOX_MONITORING_CHART_EVENT_LABEL_TOP_PX = 12
export const SANDBOX_MONITORING_PERCENT_MAX = 100

export const SANDBOX_LIFECYCLE_EVENT_CREATED = 'sandbox.lifecycle.created'
export const SANDBOX_LIFECYCLE_EVENT_PAUSED = 'sandbox.lifecycle.paused'
export const SANDBOX_LIFECYCLE_EVENT_RESUMED = 'sandbox.lifecycle.resumed'
export const SANDBOX_LIFECYCLE_EVENT_KILLED = 'sandbox.lifecycle.killed'

export const SANDBOX_MONITORING_TIME_LABEL_FORMAT_OPTIONS: Intl.DateTimeFormatOptions =
  {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }
