import {
  millisecondsInHour,
  millisecondsInMinute,
  millisecondsInSecond,
} from 'date-fns/constants'

export const SANDBOX_MONITORING_DEFAULT_RANGE_MS = millisecondsInHour
export const SANDBOX_MONITORING_MIN_RANGE_MS = 90 * millisecondsInSecond
export const SANDBOX_MONITORING_LIVE_POLLING_MS = 10_000

export const SANDBOX_MONITORING_QUERY_START_PARAM = 'start'
export const SANDBOX_MONITORING_QUERY_END_PARAM = 'end'
export const SANDBOX_MONITORING_QUERY_LIVE_PARAM = 'live'
export const SANDBOX_MONITORING_QUERY_LIVE_TRUE = '1'
export const SANDBOX_MONITORING_QUERY_LIVE_FALSE = '0'
export const SANDBOX_MONITORING_METRICS_FETCH_ERROR_MESSAGE =
  'Failed to fetch sandbox monitoring metrics.'

export const SANDBOX_MONITORING_PRESET_MATCH_TOLERANCE_MS = millisecondsInMinute

export const SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_ID = 'full-lifecycle'
export const SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_SHORTCUT = 'FULL'
export const SANDBOX_MONITORING_FIRST_15_MINUTES_PRESET_ID = 'first-15m'
export const SANDBOX_MONITORING_FIRST_15_MINUTES_PRESET_SHORTCUT = 'F15'
export const SANDBOX_MONITORING_FIRST_HOUR_PRESET_ID = 'first-1h'
export const SANDBOX_MONITORING_FIRST_HOUR_PRESET_SHORTCUT = 'F1H'
export const SANDBOX_MONITORING_LAST_15_MINUTES_PRESET_ID = 'last-15m'
export const SANDBOX_MONITORING_LAST_15_MINUTES_PRESET_SHORTCUT = 'L15'
export const SANDBOX_MONITORING_LAST_HOUR_PRESET_ID = 'last-1h'
export const SANDBOX_MONITORING_LAST_HOUR_PRESET_SHORTCUT = 'L1H'
export const SANDBOX_MONITORING_LAST_6_HOURS_PRESET_ID = 'last-6h'
export const SANDBOX_MONITORING_LAST_6_HOURS_PRESET_SHORTCUT = 'L6H'

export const SANDBOX_MONITORING_CPU_SERIES_ID = 'cpu'
export const SANDBOX_MONITORING_RAM_SERIES_ID = 'ram'
export const SANDBOX_MONITORING_DISK_SERIES_ID = 'disk'
export const SANDBOX_MONITORING_CPU_SERIES_LABEL = 'CPU'
export const SANDBOX_MONITORING_RAM_SERIES_LABEL = 'RAM'
export const SANDBOX_MONITORING_DISK_SERIES_LABEL = 'DISK'
export const SANDBOX_MONITORING_CORE_LABEL_SINGULAR = 'CORE'
export const SANDBOX_MONITORING_CORE_LABEL_PLURAL = 'CORES'
export const SANDBOX_MONITORING_VALUE_UNAVAILABLE = '--'
export const SANDBOX_MONITORING_GIGABYTE_UNIT = 'GB'
export const SANDBOX_MONITORING_METRIC_VALUE_SEPARATOR = ' · '

export const SANDBOX_MONITORING_CPU_INDICATOR_CLASS = 'bg-graph-3'
export const SANDBOX_MONITORING_RAM_INDICATOR_CLASS = 'bg-graph-1'
export const SANDBOX_MONITORING_DISK_INDICATOR_CLASS = 'bg-graph-2'
export const SANDBOX_MONITORING_CPU_LINE_COLOR_VAR = '--graph-3'
export const SANDBOX_MONITORING_CPU_AREA_COLOR_VAR = '--graph-area-3-from'
export const SANDBOX_MONITORING_CPU_AREA_TO_COLOR_VAR = '--graph-area-3-to'
export const SANDBOX_MONITORING_RAM_LINE_COLOR_VAR = '--graph-1'
export const SANDBOX_MONITORING_RAM_AREA_COLOR_VAR = '--graph-area-1-from'
export const SANDBOX_MONITORING_RAM_AREA_TO_COLOR_VAR = '--graph-area-1-to'
export const SANDBOX_MONITORING_DISK_LINE_COLOR_VAR = '--graph-2'
export const SANDBOX_MONITORING_DISK_AREA_COLOR_VAR = '--graph-area-2-from'
export const SANDBOX_MONITORING_DISK_AREA_TO_COLOR_VAR = '--graph-area-2-to'

export const SANDBOX_MONITORING_CHART_STROKE_VAR = '--stroke'
export const SANDBOX_MONITORING_CHART_FG_TERTIARY_VAR = '--fg-tertiary'
export const SANDBOX_MONITORING_CHART_FONT_MONO_VAR = '--font-mono'
export const SANDBOX_MONITORING_CHART_FALLBACK_STROKE = '#000'
export const SANDBOX_MONITORING_CHART_FALLBACK_FG_TERTIARY = '#666'
export const SANDBOX_MONITORING_CHART_FALLBACK_FONT_MONO = 'monospace'
export const SANDBOX_MONITORING_CHART_GROUP = 'sandbox-monitoring'
export const SANDBOX_MONITORING_CHART_STACK_ID = 'sandbox-resource'
export const SANDBOX_MONITORING_CHART_BRUSH_TYPE = 'lineX'
export const SANDBOX_MONITORING_CHART_BRUSH_MODE = 'single'
export const SANDBOX_MONITORING_CHART_LINE_WIDTH = 1
export const SANDBOX_MONITORING_CHART_AREA_OPACITY = 0.18
export const SANDBOX_MONITORING_CHART_OUT_OF_BRUSH_ALPHA = 0.25
export const SANDBOX_MONITORING_CHART_AXIS_LABEL_FONT_SIZE = 12
export const SANDBOX_MONITORING_CHART_Y_AXIS_SCALE_FACTOR = 1.5
export const SANDBOX_MONITORING_CHART_MIN_STEP_MS = millisecondsInSecond
export const SANDBOX_MONITORING_CHART_LIVE_WINDOW_MS = 2 * millisecondsInMinute
export const SANDBOX_MONITORING_CHART_LIVE_OUTER_DOT_SIZE = 16
export const SANDBOX_MONITORING_CHART_LIVE_MIDDLE_DOT_SIZE = 10
export const SANDBOX_MONITORING_CHART_LIVE_INNER_DOT_SIZE = 6
export const SANDBOX_MONITORING_PERCENT_MAX = 100
export const SANDBOX_MONITORING_BYTES_IN_GIGABYTE = 1024 * 1024 * 1024

export const SANDBOX_MONITORING_TIME_LABEL_FORMAT_OPTIONS: Intl.DateTimeFormatOptions =
  {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }
