import {
  millisecondsInDay,
  millisecondsInHour,
  millisecondsInSecond,
} from 'date-fns/constants'

export const SANDBOX_MONITORING_METRICS_RETENTION_MS = 7 * millisecondsInDay
export const SANDBOX_MONITORING_DEFAULT_RANGE_MS = millisecondsInHour
export const SANDBOX_MONITORING_MIN_RANGE_MS = 10 * millisecondsInSecond
export const SANDBOX_MONITORING_MAX_RANGE_MS = 31 * millisecondsInDay
export const SANDBOX_MONITORING_LIFECYCLE_PADDING_STEPS = 2
export const SANDBOX_MONITORING_LIVE_POLLING_MS = 5_000
export const SANDBOX_MONITORING_CUSTOM_END_FUTURE_MS = millisecondsInHour
export const SANDBOX_MONITORING_MIN_TIMESTAMP_MS = -8_640_000_000_000_000
export const SANDBOX_MONITORING_MAX_TIMESTAMP_MS = 8_640_000_000_000_000

export const SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_ID = 'full-lifecycle'
export const SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_SHORTCUT = 'FULL'
export const SANDBOX_MONITORING_FIRST_1_MINUTE_PRESET_ID = 'first-1m'
export const SANDBOX_MONITORING_FIRST_1_MINUTE_PRESET_SHORTCUT = 'F1'
export const SANDBOX_MONITORING_FIRST_5_MINUTES_PRESET_ID = 'first-5m'
export const SANDBOX_MONITORING_FIRST_5_MINUTES_PRESET_SHORTCUT = 'F5'
export const SANDBOX_MONITORING_LAST_1_MINUTE_PRESET_ID = 'last-1m'
export const SANDBOX_MONITORING_LAST_1_MINUTE_PRESET_SHORTCUT = 'L1'
export const SANDBOX_MONITORING_LAST_5_MINUTES_PRESET_ID = 'last-5m'
export const SANDBOX_MONITORING_LAST_5_MINUTES_PRESET_SHORTCUT = 'L5'
export const SANDBOX_MONITORING_LAST_15_MINUTES_PRESET_ID = 'last-15m'
export const SANDBOX_MONITORING_LAST_15_MINUTES_PRESET_SHORTCUT = 'L15'
export const SANDBOX_MONITORING_LAST_30_MINUTES_PRESET_ID = 'last-30m'
export const SANDBOX_MONITORING_LAST_30_MINUTES_PRESET_SHORTCUT = 'L30'

export const SANDBOX_MONITORING_DEFAULT_PRESET_ID =
  SANDBOX_MONITORING_FULL_LIFECYCLE_PRESET_ID

export const SANDBOX_MONITORING_CPU_SERIES_ID = 'cpu'
export const SANDBOX_MONITORING_RAM_SERIES_ID = 'ram'
export const SANDBOX_MONITORING_DISK_SERIES_ID = 'disk'
export const SANDBOX_MONITORING_CPU_SERIES_LABEL = 'CPU'
export const SANDBOX_MONITORING_RAM_SERIES_LABEL = 'RAM'
export const SANDBOX_MONITORING_DISK_SERIES_LABEL = 'DISK'
export const SANDBOX_MONITORING_CORE_LABEL_SINGULAR = 'CORE'
export const SANDBOX_MONITORING_CORE_LABEL_PLURAL = 'CORES'
export const SANDBOX_MONITORING_VALUE_UNAVAILABLE = '--'
export const SANDBOX_MONITORING_GIGABYTE_UNIT = 'GB'
export const SANDBOX_MONITORING_METRIC_VALUE_SEPARATOR = ' · '

export const SANDBOX_MONITORING_CPU_INDICATOR_CLASS = 'bg-graph-3'
export const SANDBOX_MONITORING_RAM_INDICATOR_CLASS = 'bg-graph-1'
export const SANDBOX_MONITORING_DISK_INDICATOR_CLASS = 'bg-graph-2'
export const SANDBOX_MONITORING_CPU_LINE_COLOR_VAR = '--graph-3'
export const SANDBOX_MONITORING_CPU_AREA_COLOR_VAR = '--graph-area-3-from'
export const SANDBOX_MONITORING_CPU_AREA_TO_COLOR_VAR = '--graph-area-3-to'
export const SANDBOX_MONITORING_RAM_LINE_COLOR_VAR = '--graph-1'
export const SANDBOX_MONITORING_RAM_AREA_COLOR_VAR = '--graph-area-1-from'
export const SANDBOX_MONITORING_RAM_AREA_TO_COLOR_VAR = '--graph-area-1-to'
export const SANDBOX_MONITORING_DISK_LINE_COLOR_VAR = '--graph-2'
export const SANDBOX_MONITORING_DISK_AREA_COLOR_VAR = '--graph-area-2-from'
export const SANDBOX_MONITORING_DISK_AREA_TO_COLOR_VAR = '--graph-area-2-to'

export const SANDBOX_MONITORING_CHART_STROKE_VAR = '--stroke'
export const SANDBOX_MONITORING_CHART_FG_TERTIARY_VAR = '--fg-tertiary'
export const SANDBOX_MONITORING_CHART_FONT_MONO_VAR = '--font-mono'
export const SANDBOX_MONITORING_CHART_FALLBACK_STROKE = '#000'
export const SANDBOX_MONITORING_CHART_FALLBACK_FG_TERTIARY = '#666'
export const SANDBOX_MONITORING_CHART_FALLBACK_FONT_MONO = 'monospace'
export const SANDBOX_MONITORING_CHART_GROUP = 'sandbox-monitoring'
export const SANDBOX_MONITORING_CHART_BRUSH_TYPE = 'lineX'
export const SANDBOX_MONITORING_CHART_BRUSH_MODE = 'single'
export const SANDBOX_MONITORING_CHART_LINE_WIDTH = 1
export const SANDBOX_MONITORING_CHART_AREA_OPACITY = 0.18
export const SANDBOX_MONITORING_CHART_CONNECTOR_LINE_OPACITY = 0.8
export const SANDBOX_MONITORING_CHART_OUT_OF_BRUSH_ALPHA = 0.25
export const SANDBOX_MONITORING_CHART_AXIS_LABEL_FONT_SIZE = 12
export const SANDBOX_MONITORING_CHART_Y_AXIS_SCALE_FACTOR = 1.5
export const SANDBOX_MONITORING_CHART_EVENT_LINE_BASE_OPACITY = 0.35
export const SANDBOX_MONITORING_CHART_LIVE_WINDOW_STEPS = 2
export const SANDBOX_MONITORING_CHART_LIVE_OUTER_DOT_SIZE = 16
export const SANDBOX_MONITORING_CHART_LIVE_MIDDLE_DOT_SIZE = 10
export const SANDBOX_MONITORING_CHART_LIVE_INNER_DOT_SIZE = 6
export const SANDBOX_MONITORING_PERCENT_MAX = 100
export const SANDBOX_MONITORING_CHART_FG_VAR = '--fg'
export const SANDBOX_MONITORING_CHART_MARKER_RIGHT_THRESHOLD_PX = 86
export const SANDBOX_MONITORING_CHART_MARKER_OVERLAP_THRESHOLD_PX = 24
export const SANDBOX_MONITORING_CHART_MARKER_LABEL_VERTICAL_GAP_PX = 20
export const SANDBOX_MONITORING_CHART_EVENT_LABEL_TOP_PX = 12
export const SANDBOX_MONITORING_CHART_EVENT_LABEL_TOP_MOBILE_PX = 4
export const SANDBOX_MONITORING_CHART_EVENT_LABEL_OVERLAP_GAP_PX = 6
export const SANDBOX_MONITORING_CHART_EVENT_LABEL_STAGGER_STEP_PX = 30
export const SANDBOX_MONITORING_CHART_EVENT_ICON_SIZE = 12
export const SANDBOX_MONITORING_CHART_EVENT_BORDER_OPACITY = 0.12
export const SANDBOX_MONITORING_CHART_MARKER_BG_OPACITY = 0.1
export const SANDBOX_MONITORING_CHART_MARKER_BORDER_OPACITY = 0.12
export const SANDBOX_MONITORING_OVERFETCH_RATIO = 0.02
export const SANDBOX_MONITORING_OVERFETCH_MIN_MS = 30 * millisecondsInSecond

export const SANDBOX_MONITORING_BYTES_IN_GIGABYTE = 1024 * 1024 * 1024

export const SANDBOX_LIFECYCLE_EVENT_CREATED = 'sandbox.lifecycle.created'
export const SANDBOX_LIFECYCLE_EVENT_PAUSED = 'sandbox.lifecycle.paused'
export const SANDBOX_LIFECYCLE_EVENT_RESUMED = 'sandbox.lifecycle.resumed'
export const SANDBOX_LIFECYCLE_EVENT_KILLED = 'sandbox.lifecycle.killed'

export const SANDBOX_MONITORING_TIME_LABEL_FORMAT_OPTIONS: Intl.DateTimeFormatOptions =
  {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }
