name: Dependencies

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  knip:
    name: Knip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.20"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Knip
        run: bun run knip
